### ISSUE TITLE
fetchNoCors 500 error

### ISSUE THREAD

**Issue by Emiliopg91** [SteamDeckHomebrew/loader-api#8]
hi guys
an issue here

I migrated to @decky/api and everything works ok except fetchNoCors:
I invoke :
await fetchNoCors(
        "https://raw.githubusercontent.com/......<rest of url>",
        { method: "GET" }
    );

and in CEF console i see 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

the URL is OK and respond with 200 and right response body on browsers and postman

**Comment by Emiliopg91** [comment]
more info:

sep 18 12:41:14 RogAllyX PluginLoader[32093]: [utilities][INFO]: Preparing GET request to https://raw.githubusercontent.com/..../package.json
sep 18 12:41:15 RogAllyX PluginLoader[32093]: [web_protocol][ERROR]: Error handling request
sep 18 12:41:15 RogAllyX PluginLoader[32093]: Traceback (most recent call last):
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp/web_protocol.py", line 452, in _handle_request
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp/web_app.py", line 543, in _handle
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp/web_middlewares.py", line 114, in impl
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "decky_loader/helpers.py", line 52, in csrf_middleware
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "decky_loader/utilities.py", line 194, in http_request
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp/web_response.py", line 417, in prepare
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp/web_response.py", line 424, in _start
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp/web_request.py", line 901, in _prepare_hook
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiosignal/__init__.py", line 36, in send
sep 18 12:41:15 RogAllyX PluginLoader[32093]:   File "aiohttp_cors/cors_config.py", line 171, in _on_response_prepare
sep 18 12:41:15 RogAllyX PluginLoader[32093]: AssertionError
